spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: yourPoolName
            auto-commit: false
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@intvmoradb04:1521:orajavadb
        username: TVM1819_TVM02_TJA10_DEV
        password: tcstvm02
        type: com.zaxxer.hikari.HikariDataSource  
   
hibernate:
              dialect: org.hibernate.dialect.OracleDialect
              
server:
  port: 7030
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
  instance:
       hostname: localhost              